export const FETCH_COURSE_REQUEST = 'FETCH_REQUEST';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_CHOICE = 'FETCH_COURSE_CHOICE';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';
export const DELETE_COURSE = 'DELETE_COURSE';
