export const FETCH_USER_REQUEST = 'FETCH_USER_RREQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_ME = 'UPDATE_ME';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const LOGOUT = 'LOGOUT';
